### ISSUE TITLE
Imports from Missing Modules in suture.py

### ISSUE THREAD

**Issue by ptrscll** [dyvasey/project-ri-strain#1]
``suture.py`` imports ``pyvista_io`` from ``gdmate.io`` and ``pyvista_vis`` from ``gdmate.visualization``, but neither of these files are in the repository (although I can add ``pyvista_vis`` if the code matches what's currently in the public ``gdmate`` repository).

**Comment by dyvasey** [comment]
`pyvista_vis` should be equivalent to what is currently in gdmate. The function called within that module (`pv_plot_2D`) is also roughly equivalent to `plot2D` in `vtk_plot.py`

The function called by `pyvista_io` (`load_clipped_meshes`) should be roughly equivalent to `vtk_plot.load_particle_meshes`. 

The calls to GDMATE in `suture.py` refer to this branch of my gdmate fork (https://github.com/dyvasey/gdmate/tree/particle_analysis), so the exact code is available there. One option would be to install that version of gdmate in your conda environment and use as written, or these functions can be copied into this new repository. Let me know if you need more clarification!

**Comment by ptrscll** [comment]
Thanks for the detailed information! I copied the functions into my fork of this repository. I think that should solve this problem (although I haven't gotten to trying out the suture script yet so there might still be issues down the line).
